### ISSUE TITLE
gulp-minify-css is deprecated

### ISSUE THREAD

**Issue by im-kulikov** [alexfedoseev/js-app-starter#1]
`npm WARN deprecated gulp-minify-css@0.4.6: Please use gulp-cssnano instead.`

**Comment by alex35mil** [comment]
Hey @im-kulikov Currently I'm not using anything from this package in my stack, so it's kinda abandoned. For more recent setups you can checkout [generator-flux-on-rails](https://github.com/alexfedoseev/generator-flux-on-rails) & [generator-react-sandbox-server](https://github.com/alexfedoseev/generator-react-sandbox-server). PR's are always welcome :+1:

**Comment by im-kulikov** [comment]
@alexfedoseev thx, understand
